### ISSUE TITLE
How to see other meanings of a word

### ISSUE THREAD

**Issue by ghost** [iurimattos/copy2Translate#1]
It shows but weird for instance I translated the error word and it gave "hata+yanlışyanılgıyanlışlıkfalsosuç" guess it was supposed to be vertical but it is not.

**Comment by iuriimattos** [comment]
What word you trying translate? i'm run on AutoHotkey v1.1.32.00 64-bit Unicode

**Comment by ghost** [comment]
I have latest Autohokey 64-bit uncideo, I was trying to translate "error" word, we can not restrict with error word, I get this problem many words that has more meaning than one.

**Comment by ghost** [comment]
@iurimattos  Thanks for helping, I updated the script also cloned in seperate folder but now script does not work at all. Script is open itself but it is not able to read clipboard history I guess. I do copy anything but I could not get any result of it. Also I have a question, I could use it before this patch but it was closed by itself automatically and I do not know why. Thanks again.

**Comment by iuriimattos** [comment]
@toprak Which **Microsoft Visual C++ Redistributable** versions you have installed?

**Comment by ghost** [comment]
@iurimattos I guess all of them, since 2005 to 2019

**Comment by iuriimattos** [comment]
@toprak i returned the initial version and applied a fix to resolve this issue, test now.

**Comment by ghost** [comment]
it works now ty
